/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Mon Oct  9 12:52:38 2017"
#define BUILD_TIME (1507571558L)

#define VERSION_NUMBER 0x03060002UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c517dUL
#define VERSION_SANITY2 0xe0c24010UL
#define VERSION_SANITY3 0x00028000UL

#define VERSION_STRING "3.6.0"
#define VERSION_ID \
 "Unix NetHack Version 3.6.0 - last build Mon Oct  9 12:52:38 2017."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.0 Unix, built Oct  9 12:52:38 2017."

