package rec.games.roguelike.nh4j;

public enum ART {

	NONE(0),
	
	EXCALIBUR(1),
	STORMBRINGER(2),
	MJOLLNIR(3),
    CLEAVER(4),
	GRIMTOOTH(5),
	ORCRIST(6),
	STING(7),
	MAGICBANE(8),
	FROST_BRAND(9),
	FIRE_BRAND(10),
	DRAGONBANE(11),
	DEMONBANE(12),
	WEREBANE(13),
	GRAYSWANDIR(14),
	GIANTSLAYER(15),
	OGRESMASHER(16),
	TROLLSBANE(17),
	VORPAL_BLADE(18),
	SNICKERSNEE(19),
	SUNSWORD(20),
	ORB_OF_DETECTION(21),
	HEART_OF_AHRIMAN(22),
	SCEPTRE_OF_MIGHT(23),
	STAFF_OF_AESCULAPIUS(24),
	MAGIC_MIRROR_OF_MERLIN(25),
	EYES_OF_THE_OVERWORLD(26),
	MITRE_OF_HOLINESS(27),
	LONGBOW_OF_DIANA(28),
	MASTER_KEY_OF_THIEVERY(29),
	TSURUGI_OF_MURAMASA(30),
	YENDORIAN_EXPRESS_CARD(31),
	ORB_OF_FATE(32),
	EYE_OF_THE_AETHIOPICA(33);
	
	private int id;
	
	ART(int id)
	{
		this.id = id;
	}

	public int id()
	{
		return this.id;
	}
  
}
